name: Deploy to Production

on:
  push:
    branches:
      - main  # หรือชื่อ branch ที่คุณต้องการให้ทำงานเมื่อ push ไป

jobs:
  deploy:
    runs-on: ubuntu-latest  # ใช้ Ubuntu ในการรัน

    steps:
      # 1. ตรวจสอบและดึงข้อมูลจาก repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. ตั้งค่า SSH สำหรับการเชื่อมต่อไปยังเซิร์ฟเวอร์
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # ใช้ private key ที่เก็บใน GitHub secrets

      # 3. เปลี่ยนไปยังโฟลเดอร์ frontend/
      - name: Go to frontend directory
        run: cd frontend  # เปลี่ยนไปที่โฟลเดอร์ที่มี package.json

      # 4. ติดตั้ง dependencies ด้วย Yarn
      - name: Install dependencies
        run: yarn install  # ติดตั้ง dependencies

      # 5. Build โปรเจกต์
      - name: Build project
        run: yarn build  # สั่งให้ build โปรเจกต์

      # 6. เชื่อมต่อกับเซิร์ฟเวอร์และ deploy
      - name: Deploy to server
        run: |
          ssh user@your-server-ip "cd /path/to/your/project && git pull origin main && yarn install && yarn build && pm2 restart your-app-name"
