name: Deploy

on:
  push:
    branches:
      - main  # ทำงานเมื่อมีการ push ไปที่ branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Set up Node.js (สำหรับทั้ง frontend และ backend)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # ใช้ Node.js version ที่ต้องการ

      # 3. Install and build frontend (ทำงานในโฟลเดอร์ frontend)
      - name: Install dependencies and build frontend
        run: |
          cd frontend  # เข้าไปที่โฟลเดอร์ frontend
          yarn install  # ติดตั้ง dependencies
          yarn build  # สร้างโปรเจกต์
        working-directory: ./frontend  # กำหนด working directory ให้เป็น frontend

      # 4. Install and build backend (ทำงานในโฟลเดอร์ backend)
      - name: Install dependencies and build backend
        run: |
          cd backend  # เข้าไปที่โฟลเดอร์ backend
          yarn install  # ติดตั้ง dependencies
          yarn build  # สร้างโปรเจกต์
        working-directory: ./backend  # กำหนด working directory ให้เป็น backend

      # 5. Deploy หรือขั้นตอนอื่นๆ
      - name: Deploy backend and frontend (ถ้ามี)
        run: |
          # ขั้นตอนการ deploy หรือคำสั่งอื่นๆ ที่คุณต้องการ
          echo "Deploying backend and frontend"
